config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show]

  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :likes, only: [:create, :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
    resources :bookmarks, only: [:create, :destroy], shallow: true
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "posts#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :images
  belongs_to :user

  validates :images, presence: true
  has_many :likes, -> {order(:created_at => :desc)}
  has_many :comments, -> {order(:created_at => :desc)}
  has_many :bookmarks

  def is_belongs_to? user
    Post.find_by(user_id: user.id, id: id)
  end

  def is_liked user
    Like.find_by(user_id: user.id, post_id: id)
  end

  def is_bookmarked user
    Bookmark.find_by(user_id: user.id, post_id: id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :password_confirmation])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :remember_me])
    end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  def create
    @bookmark = current_user.bookmarks.build(bookmark_params)
    if @bookmark.save
      @post = @bookmark.post
      @is_bookmarked = @bookmark
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @post = @bookmark.post
    if @bookmark.destroy
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  private
  def bookmark_params
    params.permit :user_id, :post_id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @comments = @post.comments.includes(:user)
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      @post = @comment.post
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  private
  def comment_params
    params.required(:comment).permit :user_id, :post_id, :content
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index ; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  private
  def like_params
    params.permit :post_id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: "Post was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    if @post.user == current_user
      if @post.destroy
        flash[:notice] = "Post deleted!"
      else
        flash[:alert] = "Something went wrong ..."
      end
    else
      flash[:notice] = "You don't have permission to do that!"
    end
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:caption, images: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.search(params[:term])
    respond_to :js
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.includes(:likes, :comments)
    @saved = Post.joins(:bookmarks).where("bookmarks.user_id=?", current_user.id).
      includes(:likes, :comments) if @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
<% else %>
Please log in or sign_in to check all the posts.
<% end %>
<%= user_signed_in? %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
<div class="container-fluid">
  <div class="navbar-header">
    <%= link_to "Soc.io", root_path, class: 'logo' %>
  </div>
  <ul class="nav navbar-nav">
    <li class="active"><%= link_to "Home", root_path %></li>
    <li><a href="#">Profile</a></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
  <% unless user_signed_in? %>
    <li><%= link_to "<span class='glyphicon glyphicon-user'></span> Sign Up".html_safe, new_user_registration_path %></li>
    <li><%= link_to "<span class='glyphicon glyphicon-log-in'></span> Login".html_safe, new_user_session_path %></li>
  <% else %>
    <li>
      <%= button_to destroy_user_session_path, method: :delete, class: "btn btn-log-out" do %>
        <span class='glyphicon glyphicon-log-out'></span> Logout
      <% end %>
    </li>
  <% end %>
  </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialMediaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.umd.min.js"
    ></script>
  </body>
</html>

app/views/posts/_bookmark_icon.html.erb
<% if is_bookmarked.present? %>
  <%= link_to "Bookmarked", bookmark_path(is_bookmarked), data: { turbo_method: "delete", remote: true },
    class: "core-sprite bookmarked hide-text" %>
<% else %>
  <%= link_to "Bookmark", post_bookmarks_path(post), data: { turbo_method: "post", remote: true },
    remote: true, class: "core-sprite bookmark hide-text" %>
<% end %>

app/views/posts/_comment_form.html.erb
<%= form_for [post, Comment.new], :html => {:class => "w-100"}, remote: true do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :post_id, value: post.id %>
  <%= f.text_field :content, class: "form-control comment-input border-0",
     placeholder: "Add a comment ...", autocomplete: :off %>
<% end %>

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "Delete comment", comment_path(comment),
         data: { turbo_method: "delete", remote: true }, class: "core-sprite delete-comment hide-text" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user),
          class: "no-text-decoration normal-color" %>
      </strong>
    </span>
    <span><%= comment.content %></span>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <div style="padding: 10px">
    <%= form.text_field :caption, class: "form-control", placeholder: "Enter the caption" %>
    <div class="col pl-0">
      <%= form.text_field :caption, class: "form-control border-0", placeholder: "Say something about this ..." %>
    </div>
    <% if post.errors.include?(:caption) %>
      <p style="color: red">
        <%= post.errors.full_messages_for(:caption).join(" ,") %>
      </p>
    <% end %>
  </div>

  <div style="padding: 10px">
    <%= form.file_field :images, multiple:true %>
  </div>

  <div style="padding: 10px">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_like_icon.html.erb
<% if is_liked.present? %>
  <%= link_to "Love", like_path(is_liked), data: { turbo_method: "delete", remote: true },
    class: "core-sprite loved hide-text" %>
<% else %>
  <%= link_to "Loved", post_likes_path(post), data: { turbo_method: "post", remote: true },
    class: "core-sprite love hide-text" %>
<% end %>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
      <% if likes.size == 1 %>
          <%= like.user.name %> </strong> like this
      <% elsif like == likes.last %>
          </strong>and<strong>
  <%= + like.user.name %></strong> like this
      <% elsif index > 1 %>
          </strong><%= "and " + (likes.size-index).to_s + " others " %> like this
          <% break %>
      <% elsif index==likes.size-2 || index==1%>
          <%= like.user.name %>
      <% else %>
          <%= like.user.name + ", " %>
      <% end %>
  <% end %>
  </strong>

app/views/posts/_photos.html.erb
<%
=begin%>
 <%= link_to post_path(post) do %>
  <% if post.images.size == 1 %>
    <%= image_tag post.images.first, class: "card-img-top", style: "object-fit: contain; height: 400px;" %>
  <% else %>
    <div class="carousel slide" data-ride="carousel" id="carousel-post-<%= @post.id %>">
      <div class="carousel-inner">
        <% post.images.each do |photo| %>
          <% if photo == post.images.first %>
            <div class="carousel-item active">
          <% else %>
            <div class="carousel-item">
          <% end %>
              <%= image_tag photo, class: "card-img-top", style: "object-fit: contain; height: 400px;" %>
            </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carousel-post-<%= @post.id %>" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-post-<%= @post.id %>" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  <% end %>
<% end %> 
<%
=end%>

<div class="card" style="margin-top: 20px; width: 45rem; border: 4px solid black">
  <%= image_tag post.images.first, class: "card-img-top", style: "object-fit: contain; width: 44rem;" %>
  <div class="card-body" style="margin-top: 15px">
    <p class="card-text text-center">
      <%= post.caption %>
    </p>
  </div>
</div>

app/views/posts/_posts_list.html.erb
<%
=begin%>
 <% @posts.each do |post| %>
  <div style="display: flex; justify-content: center; text-align: center;">
    <div id="<%= dom_id post %>" style="background-color: grey; margin: 20px;">
      <div style="display: flex;">
        <%= image_tag(post.images.first, style: "object-fit: contain; width: 200px; height: 200px;") %>
      </div>
      <div class="card" style="">
        <div class="card-body">
          <h5 class="card-title"><%= post.caption %></h5>
        </div>
      </div>
    </div>
  </div>
<% end %> 
<%
=end%>

<% @posts.each do |post| %>
 <div class="card mt-3 post">
 <div class="card-header d-flex align-items-center">
 <%= link_to user_path(post.user), class: "no-text-decoration" do %>
        <%= image_tag 'icon.png', class: "post-author-icon" %>
      <% end %>
      <%= link_to user_path(post.user), class: "normal-color no-text-decoration",
        title: post.user.name do %>
        <strong><%= post.user.name %></strong>
      <% end %> 

      <% if post.is_belongs_to? current_user %>
        <%= link_to post_path(post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
          <i class="far fa-trash-alt" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </div>  

    <%= render "photos", {post: post} %>

 <div class="card-body">
      <div class="row actions">
        <div id="like-icon-post-<%= post.id.to_s %>">
          <%= render "like_icon", {is_liked: post.is_liked(current_user), post: post} %>
        </div>
        <a href="#" class="core-sprite comment hide-text">Comment</a>
        <div id="bookmark-icon-post-<%= post.id.to_s %>" class="ml-auto">
          <%= render "bookmark_icon", {is_bookmarked: post.is_bookmarked(current_user), post: post} %>
        </div>
      </div>
      <div id="like-text-post-<%= post.id.to_s %>">
        <%= render "like_text", {likes: post.likes} %>
      </div>
      <div>
        <span><strong><%= post.user.name %></strong></span>
        <span><%= post.caption %></span>
      </div>
      <!-- load comments -->
      <div id="comment-post-<%= post.id.to_s %>">
        <%= render 'comment_list', {post: post} %>
      </div>
      <%= link_to time_ago_in_words(post.created_at).upcase + " AGO", post_path(post),
        class: "light-color post-time no-text-decoration" %>
      <hr>
      <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
        <%= render 'comment_form', {post: post} %>
      </div>
    </div>
  </div> 
<% end %> 

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <p style="color: green"><%= notice %></p>
  <div style="display: flex; flex-direction: column; align-items: center; margin-top: 20px; width: 600px">
    <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
      <div class="card" style="display: flex; flex-direction: column; align-items: center; justify-content: center; ">
        <div class="card-header">
          <h3>Create Post</h3>
        </div>
        <div class="card-body">
          <%= form_for @post, :html => {:multipart => true} do |form| %>
            <div style="padding: 10px">
              <div class="col pl-0">
                <%= form.text_field :caption, class: "form-control border-0", placeholder: "Say something about this ..." %>
              </div>
              <% if @post.errors.include?(:caption) %>
                <p style="color: red">
                  <%= @post.errors.full_messages_for(:caption).join(" ,") %>
                </p>
              <% end %>
            </div>
            <div style="padding: 10px">
              <%= form.file_field :images, multiple:true %>
            </div>
            <div style="padding: 10px">
              <%= form.submit class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>

      <div id="posts" style="display: flex; flex-direction: column; align-items: center; justify-content: center; ">
        <%= render 'posts_list' %>
      </div>
    </div>
  </div>

<% else %>
  <h1>Please log_in or sign_in to see all the posts</h1>
<% end %>

app/views/posts/new.html.erb
<% if user_signed_in? %>
<h1 style="padding: 10px">New post</h1>

<div class="row">
  <%= render "form", post: @post %>
</div>
<% else %>
<h1>Please log_in or sign_in to see all the posts</h1>
<% end %>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>


<div>
  <%
=begin%>
 <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %> 
<%
=end%>
</div>

app/views/users/_post.html.erb
<% posts.each do |post| %>
  <div class="col-4">
    <%
=begin%>
 <%= link_to post_path(post) do %> 
<%
=end%>
      <div class="post-stat d-flex justify-content-center align-items-center">
        <span>
          <i class="fa fa-heart" aria-hidden="true"></i>
          <%= post.likes.size %>
          <i class="ml-3 fa fa-comment" aria-hidden="true"></i>
          <%= post.comments.size %>
        </span>
      </div>
      <%= image_tag post.images.first, class: "", style: 'width: 100px, height: 100px' %>
    <%
=begin%>
 <% end %> 
<%
=end%>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="row justify-content-md-center profile-wrapper">
  <div class="col-md-4 text-center">
    <%= image_tag 'icon.png', width: '152', height: '152', class: "round-img" %>
  </div>
  <div class="col-md-8">
    <div class="row">
      <p class="username"><%= @user.name %></p>
      <% if @user == current_user %>
        <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
        <button type="button" class="core-sprite setting" data-toggle="modal" data-target="#exampleModal"></button>
      <% end %>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Settings</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="list-group text-center">
              <a href="#" class="list-group-item list-group-item-action">Change Password</a>
              <%= link_to "Log out", destroy_user_session_path, method: :delete,
                class: "list-group-item list-group-item-action" %>
              <a href="#" class="list-group-item list-group-item-action" data-dismiss="modal">Cancel</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <p class="email"><%= @user.email %></p>
    </div>
  </div>

  <div class="profile-tab">
    <% if @user == current_user %>
    <nav>
      <div class="nav nav-tabs d-flex justify-content-center" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-posts-tab" data-toggle="tab" href="#nav-posts" role="tab" aria-controls="nav-posts" aria-selected="true">POSTS</a>
        <a class="nav-item nav-link" id="nav-saved-tab" data-toggle="tab" href="#nav-saved" role="tab" aria-controls="nav-saved" aria-selected="false">SAVED</a>
      </div>
    </nav>
    <% end %>
    <div class="tab-content pb-3" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-posts" role="tabpanel" aria-labelledby="nav-posts-tab">
        <div class="row">
          <%= render "post", {posts: @posts} %>
        </div>
      </div>
      <div class="tab-pane fade" id="nav-saved" role="tabpanel" aria-labelledby="nav-saved-tab">
        <div class="row">
          <%= render "post", {posts: @saved} if @user == current_user %>
        </div>
      </div>
    </div>
  </div>
</div>